# Generated by Django 5.0 on 2024-07-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_uploaded_by_book_uploaded_on_downloadcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadcount',
            old_name='books',
            new_name='book',
        ),
    ]
