# Generated by Django 5.0 on 2024-07-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_books_downloadcount_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadcount',
            old_name='book',
            new_name='books',
        ),
    ]
