# Generated by Django 5.0 on 2024-07-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_book_downloadcount_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadcount',
            old_name='books',
            new_name='book',
        ),
    ]
